version: "3"
services:
  postgres:
    image: "ghcr.io/photonquantum/postgres-the-martian-bot:latest"
    volumes:
      - './postgresql.conf:/etc/postgresql/postgresql.conf:ro'
      - './data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
  the-martian-bot:
    image: "ghcr.io/photonquantum/the-martian-bot:latest"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://the-martian-bot:postgres@postgres/the-martian-bot
    volumes:
      - './.env:/app/.env'