on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: Test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: dtolnay/rust-toolchain@stable
        name: Setup Cargo Toolchain
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        name: Rust Cache
      - name: Check Code Format
        run: cargo fmt -- --check
      - name: Run Clippy Lints
        run: cargo clippy --workspace --all-targets --all-features --tests

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Setup Cargo Toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        name: Rust Cache
      - name: Install sqlx-cli
        uses: taiki-e/install-action@v2
        with:
          tool: sqlx-cli
      - name: Build postgres image
        uses: docker/build-push-action@v4
        with:
          context: postgres
          load: true
          tags: postgres-the-martian-bot
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Start postgres
        run: |
          docker run -d --rm --name postgres -p 5432:5432 \
            -v $PWD/postgres/postgresql.conf:/etc/postgresql/postgresql.conf:ro \
            -v $PWD/postgres/data:/var/lib/postgresql/data \
            -e POSTGRES_PASSWORD=postgres \
            postgres-the-martian-bot
      - name: Wait for postgres
        run: |
          until docker exec postgres pg_isready --username=the-martian-bot; do
            sleep 1
          done
      - name: Run migrations
        run: sqlx migrate run
        env:
          DATABASE_URL: postgresql://the-martian-bot:postgres@localhost:5432/the-martian-bot
      - name: Check .sqlx files
        run: cargo sqlx prepare --check --workspace -- --tests
        env:
          DATABASE_URL: postgresql://the-martian-bot:postgres@localhost:5432/the-martian-bot
      - name: Running Tests
        run: cargo test --workspace --all-targets --all-features

  build_image_bot:
    name: Build (bot image)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build bot image
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: the-martian-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build_image_postgres:
    name: Build (Postgres image)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build postgres image
        uses: docker/build-push-action@v5
        with:
          context: postgres
          tags: postgres-the-martian-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
